#!/usr/bin/env Rscript

## call SBEbatch.exe to process hex files
## assume folders generated by CTD_file_management.R
## set up CNV files to be processed by anaCTD.R

## use script to set-up psa files?
## need two sets of psa files, one for each instrument (turbidity vs fluorescence)
## third set of psa files: excluding turbidity and fluorescence, make it all uniform
## selected variables following "CTD processing protocol

## move psa files somewhere more visible? (and onto workspace)


## open issues
# - con (rather than .xmlcon) file doesn't include turbidity -- what do to about it?
# any way to translate con to xmlcon file? (for convenience)
# - automate .psa file setting. Currently have to go through each module, load,
# configure, save, and repeat for other instrument again.
# - it's trivially parallel problem -- but can batch process run in parallel?
#    -> on Windows, not worth the trouble! full run about 35 min
# - process only newly added files: keep log of what's been processed already!




rm (list = ls())
cWD <- getwd()
setwd ("~/")  ## needed?? good idea??? XXX  (yes, needed for batch file, at least for now)
## manually delete pre-existing outF?
unlink ("~/GISdata/LCI/CTD-processing/allCTD/CNV", recursive = TRUE)  ## careful!
sTime <- Sys.time()
print (sTime)


#################################
## user settings               ##
## define path to config files ##
#################################

#################################
conF <- list.files("~/GISdata/LCI/CTD-processing/allCTD/hex2process", pattern = "con$", recursive = TRUE, full.names = TRUE, ignore.case = TRUE)
# conF <- list.files("~/GISdata/LCI/CTD-processing/allCTD/hex2test", pattern = "con$", recursive = TRUE, full.names = TRUE, ignore.case = TRUE)

## path to psa files
# psa <- list.files ("~/GISdata/LCI/CTD-processing/Workspace/SEABIRD-psafiles/SBEDataProcessing-Win32/", ".psa$", recursive = TRUE, full.names = TRUE)
psaL <- list.files ("~/GISdata/LCI/CTD-processing/Workspace/SEABIRD-psafiles/", ".psa$", recursive = TRUE, full.names = TRUE)

## where to put results
outF <- "~/GISdata/LCI/CTD-processing/allCTD/CNV/"

## keep turbidity/fluorescence in?  (FALSE = cut them out to have things uniform)
fluo <- TRUE
# fluo <- FALSE
#################################



## create directories and temp directories
require (tools)
dir.create(outF, recursive = TRUE)
## create several temp dir that can be used from outside:
tL <- paste0 ("~/tmp/ctd/cnv", 1:6)
# tL <- c ("conversion", "filter", "align", "loop", "bin")
unlink (tL, recursive = TRUE, force = TRUE)
tLD <- paste (dirname (tL), basename(tL), sep = "/")
names (tL) <- paste0 ("t", 1:4)
inD <- dirname (conF)
outF <- paste0 (dirname (outF), "/CNV") # windows idiosyncrasy



# ## trouble shooting -- one file at a time
if (0){
# conF <- gsub ("//", "\\", conF, fixed = TRUE)
# file.path(conF, fsep = "\\")
i <- 3
j <- 99
# for (i in 1:length (conF)){
#   for (k in 1:length (tL)){dir.create (tL [k], recursive = TRUE)}
#   hexFiles <- list.files(dirname (conF [i]), ".hex$")
#   for (j in 1:length (hexFiles)){
#     l1 <- paste0 ("DatCnv /i", inD [i], "/", hexFiles [j], " /c", conF [i], " /o", tLD[1]
#                   , " /p", psa [grep ("Dat", psa)], " #m")
#     write (l1, file = "CTDbatch.txt")
#     system (paste0 ("SBEbatch.exe ", getwd (), "/CTDbatch.txt"))
#   }
#   unlink (tL, recursive = TRUE, force = TRUE)
# }
#
# rm (i, j, k)
}



## create and call batch files
## great if this could run in parallel -- probably not on Windows?
for (i in 1:length (conF)){
  #sapply (1:length (tL), FUN = function (j){dir.create (tL [j], recursive = TRUE)})
  for (j in 1:length (tL)){dir.create (tL [j], recursive = TRUE)}
  if (fluo){ # false: exclude turbidity/fluorescence
    if (length (grep ("\\.CON$", conF [i])) > 0){    # earliest con file excludes fluorescence
      psa <- psaL [grep ("SBEDataProcessing-Win32", psaL)]
    }else if (length (grep ("4141", conF [i])) > 0){ # use separate psa to preserve fluorescence/turbidity
      psa <- psaL [grep ("4141", psaL)]
    }else{
      psa <- psaL [grep ("5028", psaL)]
    }
  }else{
    psa <- psaL [grep ("SBEDataProcessing-Win32", psaL)]
  }
  l1 <- paste0 ("DatCnv /i",  inD [i], "/*.hex /c", conF[i], " /o", tLD[1], " /p", psa [grep ("DatCnv", psa)], " #m")
  l2 <- paste0 ("Filter /i",   tLD[1], "/*.cnv ",              "/o",tLD[2], " /p", psa [grep ("Filter", psa)], " #m")
  l3 <- paste0 ("AlignCTD /i", tLD[2], "/*.cnv ",              "/o",outF, " /p", psa [grep ("Align", psa)] , " #m")
  ## the lines below would do the loop-edit, and binning by depth in SBEDataProcessing as well. This results about 10 files to
  ## fail (no data). Instead, do the loopedit within OCE (see CTD_cnv-Import.R). Bin-averaging by depth will run in CTD_cleanup.R

#  l3 <- paste0 ("AlignCTD /i", tLD[2], "/*.cnv ",              "/o",tLD[3], " /p", psa [grep ("Align", psa)] , " #m")# new
#  l5 <- paste0 ("LoopEdit /i", tLD [3], "/*.cnv ",             "/o",tLD[4], " /p", psa [grep ("Loop", psa)], " #m") # new
#  l7 <- paste0 ("BinAvg /i", tLD [4], "/*.cnv ",             "/o", outF,    " /p", psa [grep ("BinAvg", psa)], " #m") # new
  # l4 <- paste0 ("CellTM    /i", t3, "/*.cnv /c", conF [i], "/o", outF, " /p", psa [4], " #m")
#  paste0 ("Derive /i", inD [i], "/*.cnv /c", conf [i], " /p", psa [6], " #m")
  ## add thermal mass or derived variables??
  bT <- paste (l1, l2, l3, sep = "\n")
#  bT <- paste (l1, l2, l3, l5, l7, sep = "\n")
  write (bT, file = "~/CTDbatch.txt")
  # efforts to suppress console output failed: invisible(), capture.output()...
  x <- system (paste0 ("SBEbatch.exe ", getwd (), "/CTDbatch.txt"), wait = TRUE, intern = TRUE)
  ## cleanup
  unlink (tL, recursive = TRUE, force = TRUE)
  unlink ("~/CTDbatch.txt")
}

rm (bT, i, j, tLD)
rm (conF, psa, outF, inD, tL, l1, l2, l3)



## write out log what has already been processed (to speed up new data)
# no record whether conversion was successful -- assume it was
# -- consider for workspace -- not worth the trouble on local machine


print (Sys.time())
print (difftime(Sys.time(), sTime))

setwd (cWD)
## EOF