#!/usr/bin/env Rscript

## call SBEbatch.exe to process hex files
## assume folders generated by CTD_file_management.R
## set up CNV files to be processed by anaCTD.R

## use script to set-up psa files?
## need two sets of psa files, one for each instrument (turbidity vs flourescence)


rm (list = ls())
setwd ("~/")
## manualy delete pre-existing outF?
unlink ("~/GISdata/LCI/CTD-startover/allCTD/CNV", recursive = TRUE)  ## careful!


################################
## define path to config files
conF <- list.files("~/GISdata/LCI/CTD-startover/allCTD/hex2process", pattern = "con$"
                   , recursive = TRUE, full.names = TRUE, ignore.case = TRUE)
## path to psa files
# psa <- list.files ("~/GISdata/LCI/CTD-startover/Workspace/SBEDataProcessing-Win32/", ".psa$", full.names = TRUE) # Jim's files
psaL <- list.files ("C:/Users/Martin.Renner/AppData/Local/", ".psa$", full.names = TRUE, recursive = TRUE) # start from scratch

## where to put results
outF <- "~/GISdata/LCI/CTD-startover/allCTD/CNVtest"
################################


## create directories and temp directories
require (tools)
dir.create(outF, recursive = TRUE)
## create several temp dir that can be used from outside:
tL <- paste0 ("~/tmp/ctd/cnv", 1:4)
unlink (tL, recursive = TRUE, force = TRUE)
tLD <- paste (dirname (tL), basename(tL), sep = "/")
names (tL) <- paste0 ("t", 1:4)
inD <- dirname (conF)

if (0){
# conF <- gsub ("//", "\\", conF, fixed = TRUE)
# file.path(conF, fsep = "\\")
i <- 3
j <- 99
# ## trouble shooting -- one file at a time
# for (i in 1:length (conF)){
#   for (k in 1:length (tL)){dir.create (tL [k], recursive = TRUE)}
#   hexFiles <- list.files(dirname (conF [i]), ".hex$")
#   for (j in 1:length (hexFiles)){
#     l1 <- paste0 ("DatCnv /i", inD [i], "/", hexFiles [j], " /c", conF [i], " /o", tLD[1]
#                   , " /p", psa [grep ("Dat", psa)], " #m")
#     write (l1, file = "CTDbatch.txt")
#     system (paste0 ("SBEbatch.exe ", getwd (), "/CTDbatch.txt"))
#   }
#   unlink (tL, recursive = TRUE, force = TRUE)
# }
#
# rm (i, j, k)
}


## create and call batch files
for (i in 1:length (conF)){
  #sapply (1:length (tL), FUN = function (j){dir.create (tL [j], recursive = TRUE)})
  for (j in 1:length (tL)){dir.create (tL [j], recursive = TRUE)}

  if (length (grep ("4141", conF [i])) > 0){ ## use separate
    psa <- psaL [grep ("4141", psaL)]
  }else{
    psa <- psaL [grep ("5028", psaL)]
  }

  l1 <- paste0 ("DatCnv /i", inD [i], "/*.hex /c", conF [i], " /o", tLD[1], " /p", psa [grep ("DatCnv", psa)], " #m")
  l2 <- paste0 ("Filter /i", tLD[1], "/*.cnv /c", conF [i], "/o", tLD[2], " /p", psa [grep ("Filter", psa)], " #m")
  l3 <- paste0 ("AlignCTD /i", tLD[2], "/*.cnv /c", conF [i], "/o", tLD[3], " /p", psa [grep ("Align", psa)], " #m")
#  l4 <- paste0 ("CellTM    /i", t3, "/*.cnv /c", conF [i], "/o", outF, " /p", psa [4], " #m")
#  paste0 ("LoopEdit /i", inD [i], "/*.cnv /c", conf [i], " /p", psa [5], " #m")
#  paste0 ("Derive /i", inD [i], "/*.cnv /c", conf [i], " /p", psa [6], " #m")
#  paste0 ("BinAvg /i", inD [i], "/*.cnv /c", conf [i], " /p", psa [7], " #m")
  bT <- paste (l1, l2, l3, sep = "\n")
  write (bT, file = "~/CTDbatch.txt")

  ## temp for testing
  # write (l1, file = "~/CTDbatch.txt")
  # write.table(l1, file = file = "~/CTDbatch.txt", append = FALSE, quote = FALSE, row.names = FALSE)
  system (paste0 ("SBEbatch.exe ", getwd (), "/CTDbatch.txt"))
   ## cleanup
  unlink (tL, recursive = TRUE, force = TRUE)
#  unlink ("~/CTDbatch.txt")
}

rm (bT, i, j, tlD)
rm (conF, psa, outF, inD, tL, pF, l1, l2, l3)

## EOF